--- 
alerting: 
  alertmanagers: 
    - 
      scheme: http
      static_configs: 
        - 
          targets: 
            - "giropops_alertmanager:9093"
global: 
  evaluation_interval: 10s
  external_labels: 
    monitor: giropops-monitoring
  scrape_interval: 10s
rule_files: 
  - alert.rules
scrape_configs: 
  - 
    job_name: node
    scrape_interval: 5s
    static_configs: 
      - 
        targets: 
          - "localhost:9090"
          - "giropops_cadvisor:8080"
          - "giropops_node-exporter:9100"
  - 
    honor_labels: true
    job_name: netdata
    metrics_path: /api/v1/allmetrics
    params: 
      format: 
        - prometheus
    scrape_interval: 5s
    static_configs: 
      - 
        targets: 
          - "YOUR_NETDATA_IP:19999"
  - 
    job_name: blackbox
    metrics_path: /probe
    params: 
      module: 
        - http_2xx
    relabel_configs: 
      - 
        source_labels: 
          - __address__
        target_label: __param_target
      - 
        source_labels: 
          - __param_target
        target_label: instance
      - 
        replacement: "YOUR_BLACKBOX_IP:9115"
        target_label: __address__
    static_configs: 
      - 
        targets: 
          - "http://example.com"
          - "https://www.mysite.com"
